[build]
builder = "Dockerfile"
buildCommand = "echo building!"

[deploy]
preDeployCommand = ["npm run prepare:prod"]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "never"
